apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: slurm_acct_db
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-auth-secret
                  key: password
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
            - name: MYSQL_USER
              value: "slurm"
          image: {{ .Values.sqlImage }}
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: var-lib-mysql
      hostname: mysql
      restartPolicy: Always
      volumes:
        - name: var-lib-mysql
          persistentVolumeClaim:
            claimName: var-lib-mysql
status: {}
