apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: slurmd
spec:
  replicas: {{ .Values.replicas.slurmd }}
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmd
      app.kubernetes.io/part-of: slurm-docker-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmd
        app.kubernetes.io/part-of: slurm-docker-cluster
    spec:
      containers:
        - args:
            - slurmd
          image: {{ .Values.sdcImage }}
          name: slurmd
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
            - mountPath: {{ .Values.sharedDirectory.mountPath }}
              name: slurm-jobdir
            - mountPath: /tempmounts/munge.key
              name: munge-key-secret
              subPath: munge.key
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          nfs:
            server: {{ .Values.nfs.server }}
            path: {{ .Values.nfs.path }}
        - name: slurm-config-volume
          configMap:
            name: {{ .Values.configmaps.slurmConf }}
        - name: munge-key-secret
          secret:
            secretName: {{ .Values.secrets.mungeKey }}
status: {}
